### ISSUE TITLE
Error message in Chinese

### ISSUE THREAD

**Issue by krysalead** [ionic2-ninja/emiya-ionic2-router#2]
Hi,

First thanks for the lib it looks pretty good so far. I got some remarks 
I was using a wrong configuration structure and I got this 
不满足进入该页面所需条件  -> Does not meet the conditions required to enter the page 
Also it could be good to type your config so we can have typescript doing some sanity checks.
It looks that your lib is really powerfull but a bit more of documentation will be great.
I noticed also that in your documenation you mention Router instead of Token object during import in both places router doc and token doc.

Thanks again for your work

**Comment by emiyalee1005** [comment]
you are right,不满足进入该页面所需条件 means "Does not meet the conditions required to enter the page".
Basically you should get err code&message from the promise's response. The chinese you found from console it's some debug info I forgot to delete.
And I will add interface and type checking to router in the future;

**Comment by emiyalee1005** [comment]
"I noticed also that in your documenation you mention Router instead of Token object during import in both places router doc and token doc.” =>it's a document mistake and will get corrected later.
Again thanks for feedback.

**Comment by emiyalee1005** [comment]
interface added in v1.4.6
